### ISSUE TITLE
Not able to clone replo into arduino folder

### ISSUE THREAD

**Issue by Trishanu123** [pschatzmann/arduino-espeak-ng#16]
The bash cammand "git clone pschatzmann/arduino-espeak-ng.git" is not working. It is throwing error on mac called " fatal: repository 'pschatzmann/arduino-espeak-ng.git' does not exist"

**Comment by pschatzmann** [comment]
It should be https://github.com/pschatzmann/arduino-espeak-ng.git

You can double check the url by clicking on the code button...

**Comment by Trishanu123** [comment]
yes now its solved thank you.

**Comment by Trishanu123** [comment]
Hello, I need some help with using this library with the esp32s3. I would
appreciate it if you can come on a call with me.
